#dataset parameters
experiment_name: "perez_mito"
num_classes: 1
class_names: 
  - "mito"

#set the directories for data and models
data_dir: "/perez/mito/train"
model_dir: "/RETINA/perez_mito/checkpoint_92"
logging: False
save_interval: 500
num_save_checkpoints: 6
resume: ""

#hyperparameters
bsz: # customized based on GPU memory
jobs: 4
#choice of none, layer4, layer3, layer2, layer 1, or all
finetune_layer: "none"
unfreeze_encoder_bn: False
encoder: "resnet50"
transformer_layer: 12
pretrain: True
pretrain_file: '/RETINA/checkpoint_pretrain/pretrain_200.pt'
finetuned: False
finetuned_file: ''

lr: 0.003
wd: 0.1
optim: "AdamW"
lr_policy: ""

#parameter only for SGD optim; AdamW uses default momentum values
momentum: 0.9

#iterations are used for Poly and OneCycle,
#epochs are used for MultiStep
iters: 3000

#parameters specific for Poly lr_policy
power: 0.9

#set pixel norm values
norms:
    mean: 0.35047498
    std: 0.01674651
  
#currently only IoU is supported
metrics:
  - "IoU"
  
#number of times to print/record metrics for 
#train and validation data over the entire
#training run
num_prints: 30

#list the augmentations to use during training
augmentations:
  - aug: "PadIfNeeded"
    min_height: 224
    min_width: 224
  - aug: "RandomResizedCrop"
    height: 224
    width: 224
    scale:
      - 0.08
      - 1.0
    ratio:
      - 0.5
      - 1.5
  - aug: "Rotate"
    limit: 180
  - aug: "RandomBrightnessContrast"
    brightness_limit: 0.3
    contrast_limit: 0.3
  - aug: "HorizontalFlip"
  - aug: "VerticalFlip"
  
###INFERENCE SECTION 2D###
test_dir2d: ""
threshold2d: 0.5
instance_match2d: True
eval_classes2d:
  - 1
save_dir2d: ''
