# Guay dataset parameters
experiment_name: "guay"
num_classes: 7
class_names: 
  - "back"
  - "cell"
  - "mito"
  - "can_chan"
  - "alpha_gran"
  - "dense_gran"
  - "dense_gran_core"
  
class_weights:
  - 0.1
  - 0.1
  - 1
  - 1
  - 0.1
  - 3
  - 3

#set the directories for data and models
data_dir: "/guay/2d/train"
model_dir: "/RETINA/guay/checkpoint"
logging: False
save_interval: 500

resume: ""
restart_training: False

#hyperparameters
bsz: # customized based on GPU memory
jobs: 4
#choice of none, layer4, layer3, layer2, layer 1, or all
transformer_layer: 12
pretrain: True
pretrain_file: '/RETINA/checkpoint_pretrain/pretrain_200.pt'
finetuned: False
finetuned_file: ''
finetune_layer: "none"

unfreeze_encoder_bn: False

lr: 0.003
wd: 0.1
#choice of AdamW or SGD
optim: "AdamW"
iters: 3000

#parameters specific for Poly lr_policy
power: 0.9

#pixel norm valuesfor the dataset
norms:
  mean: 0.55412821
  std: 0.15759415
  
#currently only IoU is supported
metrics:
  - "IoU"
num_prints: 30

#list the augmentations to use during training
augmentations:
  - aug: "PadIfNeeded"
    min_height: 224
    min_width: 224
  - aug: "RandomResizedCrop"
    height: 224
    width: 224
    scale:
      - 0.08
      - 1.0
    ratio:
      - 0.5
      - 1.5
  - aug: "Rotate"
    limit: 180
  - aug: "RandomBrightnessContrast"
    brightness_limit: 0.3
    contrast_limit: 0.3
  - aug: "GaussNoise"
    var_limit:
      - 400
      - 1200
  - aug: "GaussianBlur"
    blur_limit: 7
  - aug: "HorizontalFlip"
  - aug: "VerticalFlip"
  
###INFERENCE SECTION 3D###
test_dir3d: ""
mode3d: "stack"
threshold3d: 0.5
eval_classes3d:
  - 2
  - 3
  - 4
  - 5
  - 6
save_dir3d: ""
 
