#dataset parameters
experiment_name: "urocell"
num_classes: 3
class_names: 
  - "back"
  - "lyso"
  - "mito"

class_weights:
  - 0.1
  - 1
  - 1

#set the directories for data and models
data_dir: "/urocell/2d/train"
model_dir: "/RETINA/urocell/checkpoint"
logging: False
norms:
    mean: 0.76752738
    std: 0.10404078
save_interval: 500
#if a .pth file is given, model training will resume
#from that checkpoint
resume: ""
restart_training: False

#hyperparameters 
bsz: # customized based on GPU memory
jobs: 4
transformer_layer: 12
pretrain: True
pretrain_file: '/RETINA/checkpoint_pretrain/pretrain_200.pt'
finetuned: False
finetuned_file: ''

lr: 0.003
wd: 0.1
#choice of AdamW or SGD
optim: "AdamW"
#choice of OneCycle, MultiStep, or Poly
lr_policy: ""

iters: 3000


#set pixel norm values
norms:
    mean: 0.27342241
    std: 0.26917548
  
#currently only IoU is supported
metrics:
  - "IoU"
  
#number of times to print/record metrics for 
#train and validation data over the entire
#training run
num_prints: 15

#list the augmentations to use during training
augmentations:
  - aug: "PadIfNeeded"
    min_height: 224
    min_width: 224
  - aug: "CropNonEmptyMaskIfExists"
    height: 224
    width: 224
    p: 0.8
  - aug: "RandomResizedCrop"
    height: 224
    width: 224
    scale:
      - 0.08
      - 1.0
    ratio:
      - 0.5
      - 1.5
  - aug: "Rotate"
    limit: 180
  - aug: "RandomBrightnessContrast"
    brightness_limit: 0.3
    contrast_limit: 0.3
  - aug: "HorizontalFlip"
  - aug: "VerticalFlip"
  

###INFERENCE SECTION 2D###
test_dir2d: ""
threshold2d: 0.5
instance_match2d: False
eval_classes2d:
  - 1
  - 2
save_dir2d: ""
